//! Generate the per-worktree `docker-compose.override.yml`. Each
//! worktree gets a unique compose project name (so containers don't
//! collide), a unique django container name, and a `command:` that
//! binds django to the worktree's `BE_PORT`. Inactive services
//! (postgres/redis/etc.) get `profiles: ["inactive"]` so they don't
//! start in the worktree — the worktree's django reaches them via
//! the main stack on `network_mode: host`.

use std::fs;
use std::path::Path;

use super::config::OrchestratorConfig;

/// Path to the override file inside a worktree's BE dir.
pub fn override_path(be_dir: &Path) -> std::path::PathBuf {
    be_dir.join("docker-compose.override.yml")
}

/// Write the override file. Idempotent — overwrites whatever's there.
pub fn write(
    cfg: &OrchestratorConfig,
    be_dir: &Path,
    short: &str,
    be_port: u16,
) -> std::io::Result<()> {
    let project = cfg.compose_project(short);
    let container = cfg.be_container(short);
    let mut out = String::new();
    out.push_str(&format!(
        r#"# Generated by Tethys dev orchestrator — do not commit.
#
# Per-worktree django with shared infra: the services marked
# profiles: [inactive] don't start in the worktree, so the worktree
# django uses the main stack's postgres/redis (via network_mode: host).
#
# To bring this worktree's django down: docker compose -p {project} down
# To bring the whole stack down: docker compose down (in main stack).
name: {project}
services:
  django:
    container_name: {container}
    command: ./manage.py runserver_plus --nothreading 0.0.0.0:{be_port}
"#
    ));
    if !cfg.bind_mounts.is_empty() {
        out.push_str("    volumes:\n");
        for bm in &cfg.bind_mounts {
            out.push_str(&format!(
                "      - {}:{}:ro\n",
                bm.host_path.display(),
                bm.container_path
            ));
        }
    }
    for svc in &cfg.inactive_services {
        out.push_str(&format!("  {svc}:\n    profiles: [\"inactive\"]\n"));
    }
    fs::write(override_path(be_dir), out)
}
