use std::path::{Path, PathBuf};

use schemars::{schema_for, JsonSchema};
use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};

use crate::error::{AppError, AppResult};
use crate::github::{parse_github_remote, GithubSlug};

/// The user-edited repo registry — Tethys's pointer to which repos exist on
/// disk and where their worktrees should land.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
pub struct RepoRegistry {
    /// Absolute directory where Tethys creates per-workspace worktrees. Prefer
    /// a path without spaces; macOS "Application Support" paths in particular
    /// tend to break naive setup scripts.
    pub worktree_root: PathBuf,

    /// One entry per repo you want Tethys-managed workspaces to span.
    ///
    /// TOML uses `[[repo]]` array-of-tables syntax (singular field name), but
    /// we serialize back to the frontend as `repos` (plural array).
    #[serde(default, rename(serialize = "repos", deserialize = "repo"))]
    #[schemars(rename = "repo")]
    pub repos: Vec<Repo>,

    /// Optional overrides for the `CLAUDE.md` Tethys generates at each
    /// workspace root. Omit the whole `[workspace_doc]` table to use the
    /// built-in text.
    #[serde(default)]
    pub workspace_doc: Option<WorkspaceDocConfig>,
}

/// `[workspace_doc]` in `repos.toml`.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
pub struct WorkspaceDocConfig {
    /// Markdown body of the generated workspace `CLAUDE.md`, replacing Tethys's
    /// built-in text. Tethys still prepends its `<!-- generated by tethys -->`
    /// marker line and appends a "Repo notes" section built from each repo's
    /// `claude_notes`; everything between them is yours.
    ///
    /// These placeholders are substituted: `{branch}`, `{repo_list}` (a markdown
    /// bullet per repo in the workspace), `{available_repos}` (registry repos
    /// *not* in this workspace, or a "none" phrase), `{workspace_root}`,
    /// `{clone_dir}`. Any other `{token}` is left alone and logged, so braces in
    /// prose or code fences need no escaping.
    pub body: String,
}

#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
pub struct Repo {
    /// Short stable id used in `state.json`, workspace paths, and as the
    /// UI label. Must be unique within the registry. Lowercase + dashes
    /// recommended.
    pub key: String,

    /// Git remote URL (e.g. `git@github.com:me/repo.git`). Tethys maintains
    /// its own clone under `<data_dir>/repos/<key>/` and runs every
    /// `git worktree add` against that clone — never against any checkout
    /// you maintain separately.
    pub remote_url: String,

    /// Branch new worktrees are cut from. Tethys switches the base clone to
    /// this branch (creating a local tracking branch from `origin/<branch>` if
    /// needed) before `git worktree add`. Defaults to the remote's default
    /// branch (`refs/remotes/origin/HEAD`) when unset.
    #[serde(default)]
    pub default_branch: Option<String>,

    /// Shell command run in each new worktree immediately after it's created
    /// (e.g. `pnpm install`). Optional.
    #[serde(default)]
    pub default_setup_script: Option<String>,

    /// Hard timeout for the setup script, in seconds. Defaults to 600.
    #[serde(default)]
    pub setup_timeout_secs: Option<u64>,

    /// Files to copy from the base clone into each new worktree right after
    /// `git worktree add`. Paths are relative to the clone root (e.g. `.env`,
    /// `apps/web/.env.local`). Missing sources are silently skipped; an
    /// existing file at the destination is left alone. Absolute paths and
    /// `..` segments are rejected.
    #[serde(default)]
    pub copy_files: Vec<String>,

    /// Standing context for Claude about working in this repo — the things you'd
    /// otherwise re-explain every session (e.g. "a global django container is
    /// usually already running; don't start another"). Rendered verbatim
    /// (markdown allowed) into the generated `CLAUDE.md` at the root of every
    /// workspace that includes this repo, which Claude reads whether its
    /// session runs in the repo's worktree or at the workspace root. For
    /// guidance that belongs to the code rather than to your local setup,
    /// prefer the repo's own committed `CLAUDE.md`.
    #[serde(default)]
    pub claude_notes: Option<String>,

    /// Populated at registry load time by parsing `remote_url`. `None` means
    /// the remote isn't on github.com and GitHub sync should skip this repo.
    #[serde(skip, default)]
    #[schemars(skip)]
    pub github_slug: Option<GithubSlug>,
}

/// The outcome of loading `repos.toml` at boot.
///
/// Held in Tauri-managed state as `Arc<RegistryLoad>`. Commands that need a
/// valid registry use `require()` to unwrap.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RegistryLoad {
    Ok {
        path: PathBuf,
        registry: RepoRegistry,
    },
    Missing {
        path: PathBuf,
    },
    Invalid {
        path: PathBuf,
        error: String,
    },
}

impl RegistryLoad {
    pub fn load(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(s) => match toml::from_str::<RepoRegistry>(&s) {
                Ok(mut registry) => {
                    if let Err(e) = validate_worktree_root(&registry.worktree_root) {
                        warn!(error = %e, "repos.toml loaded but worktree_root is unusable");
                        return RegistryLoad::Invalid {
                            path: path.to_path_buf(),
                            error: format!("worktree_root: {e}"),
                        };
                    }
                    populate_github_slugs(&mut registry);
                    info!(
                        repos = registry.repos.len(),
                        worktree_root = %registry.worktree_root.display(),
                        "repos.toml loaded",
                    );
                    RegistryLoad::Ok {
                        path: path.to_path_buf(),
                        registry,
                    }
                }
                Err(e) => RegistryLoad::Invalid {
                    path: path.to_path_buf(),
                    error: e.to_string(),
                },
            },
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => RegistryLoad::Missing {
                path: path.to_path_buf(),
            },
            Err(e) => RegistryLoad::Invalid {
                path: path.to_path_buf(),
                error: e.to_string(),
            },
        }
    }

    pub fn require(&self) -> AppResult<&RepoRegistry> {
        match self {
            RegistryLoad::Ok { registry, .. } => Ok(registry),
            RegistryLoad::Missing { path } => Err(AppError::Other(format!(
                "repos.toml is missing at {}",
                path.display()
            ))),
            RegistryLoad::Invalid { path, error } => Err(AppError::Other(format!(
                "repos.toml at {} is invalid: {error}",
                path.display()
            ))),
        }
    }
}

impl RepoRegistry {
    pub fn find_repo(&self, key: &str) -> Option<&Repo> {
        self.repos.iter().find(|r| r.key == key)
    }

    /// The body template for generated workspace `CLAUDE.md` files: the user's
    /// if `[workspace_doc].body` is set and non-blank, else the built-in.
    pub fn workspace_doc_body(&self) -> &str {
        self.workspace_doc
            .as_ref()
            .map(|c| c.body.trim())
            .filter(|b| !b.is_empty())
            .unwrap_or(crate::workspace_doc::DEFAULT_BODY)
    }

    /// `<worktree_root>/<workspace_dir>/<repo_key>`. `workspace_dir` is the
    /// per-workspace directory name — historically a UUID, now derived from
    /// the branch via `sanitize_branch_for_dir`.
    pub fn plan_worktree_path(&self, workspace_dir: &str, repo_key: &str) -> PathBuf {
        self.worktree_root.join(workspace_dir).join(repo_key)
    }
}

/// Convert a branch name into something safe to use as a single path
/// component. Git refs disallow most path-unsafe characters (`:`, `\`, `*`,
/// `?`, `[`, `~`, `^`, space, control chars), so the only character we have
/// to translate in practice is `/`, which git uses as a hierarchy separator
/// inside refs (`feat/foo`).
pub fn sanitize_branch_for_dir(branch: &str) -> String {
    branch.replace('/', "-")
}

/// Parse each repo's remote URL into an `owner/name` slug, logging a single
/// info line per non-GitHub repo so the user knows why they won't see PR data.
fn populate_github_slugs(registry: &mut RepoRegistry) {
    for repo in &mut registry.repos {
        repo.github_slug = parse_github_remote(&repo.remote_url);
        if repo.github_slug.is_none() {
            info!(
                key = %repo.key,
                remote = %repo.remote_url,
                "repo has non-GitHub remote; skipping GitHub sync for this repo",
            );
        }
    }
}

/// Ensure `worktree_root` exists as a writable directory. Creates it if missing.
fn validate_worktree_root(root: &Path) -> AppResult<()> {
    std::fs::create_dir_all(root).map_err(|e| {
        AppError::Other(format!(
            "could not create {}: {e}",
            root.display()
        ))
    })?;
    if !root.is_dir() {
        return Err(AppError::Other(format!(
            "{} exists but is not a directory",
            root.display()
        )));
    }
    let probe = root.join(".tethys-write-probe");
    std::fs::write(&probe, b"ok").map_err(|e| {
        AppError::Other(format!("{} is not writable: {e}", root.display()))
    })?;
    let _ = std::fs::remove_file(&probe);
    Ok(())
}

/// Generate the JSON Schema for `repos.toml` and write it alongside the config
/// file so editors (Taplo / VS Code "Even Better TOML") pick it up via the
/// `#:schema` directive in the starter template.
pub fn write_schema(path: &Path) -> AppResult<()> {
    let schema = schema_for!(RepoRegistry);
    let json = serde_json::to_string_pretty(&schema)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, json)?;
    debug!(?path, "wrote repos.schema.json");
    Ok(())
}

/// Starter `repos.toml` content written when the user clicks "Open repos.toml"
/// and the file doesn't yet exist.
pub fn starter_template() -> &'static str {
    r##"#:schema ./repos.schema.json
# Tethys repo registry. Add one [[repo]] block per repo you want to work on.
#
# worktree_root: where Tethys creates per-workspace worktrees. Prefer a path
# with no spaces (e.g. ~/code/tethys-worktrees) to avoid quoting hazards in
# setup scripts.
#
# Each repo is cloned on first use into <data_dir>/repos/<key>, then every
# worktree is `git worktree add`ed from that clone — Tethys never touches
# any checkout you maintain separately.

worktree_root = "CHANGE_ME_TO_AN_ABSOLUTE_PATH"

# [[repo]]
# key = "frontend"
# remote_url = "git@github.com:me/frontend.git"
# default_branch = "main"          # defaults to the remote's default branch
# default_setup_script = "pnpm install"
# setup_timeout_secs = 600
# copy_files = [".env", "apps/web/.env.local"]
#
# # Standing context for Claude, rendered into each workspace's generated
# # CLAUDE.md. Good for local-setup facts you'd otherwise repeat every session.
# claude_notes = """
# A global django container is usually already running — don't start another.
# """

# Tethys generates a CLAUDE.md at each workspace root explaining the worktree
# layout. Uncomment to replace its wording with your own. Placeholders:
# {branch} {repo_list} {available_repos} {workspace_root} {clone_dir}.
#
# [workspace_doc]
# body = """
# # Workspace `{branch}`
#
# Repos checked out here:
#
# {repo_list}
#
# Everything you may touch is under `{workspace_root}`. Need a repo that isn't
# here? Ask me to add it — don't go read another checkout.
# """
"##
}
