//! Tethys-generated `<workspace_root>/CLAUDE.md`.
//!
//! Claude Code loads `CLAUDE.md` from the cwd *and every parent directory*, so
//! a single file at the workspace root reaches the workspace's session whether
//! it runs at the root or inside one repo's worktree — without putting an
//! untracked file inside any worktree.
//!
//! Its job is to tell Claude what this directory is (N worktrees of N repos, all
//! on one branch) and, crucially, what *isn't* here: when a repo the task needs
//! wasn't included in the workspace, the correct move is to ask Ryan to add it
//! via Tethys, not to go read some other checkout on disk.
//!
//! The prose is a template: `[workspace_doc].body` in `repos.toml` if set, else
//! [`DEFAULT_BODY`], with [`PLACEHOLDERS`] substituted. Tethys owns only the
//! marker line at the top and the per-repo "Repo notes" section at the bottom.
//!
//! The file is fully regenerated (on create, on repo-add, and at every boot) so
//! edits to the body or to `claude_notes` land without any manual step. A
//! pre-existing `CLAUDE.md` without our marker is left untouched.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use tokio::fs;
use tracing::warn;

use crate::error::{AppError, AppResult};
use crate::paths::Paths;
use crate::registry::RepoRegistry;
use crate::state::Workspace;

/// First line of every generated file. Also the guard against clobbering a
/// hand-written `CLAUDE.md` that happens to sit at a workspace root.
const MARKER: &str = "<!-- generated by tethys -->";

const FILE_NAME: &str = "CLAUDE.md";

/// The body used when `repos.toml` has no `[workspace_doc].body`. Same
/// placeholder vocabulary as a user-supplied body — see [`PLACEHOLDERS`].
pub const DEFAULT_BODY: &str = r#"# Tethys workspace: `{branch}`

This directory is a **Tethys workspace**: one unit of work spanning the git worktrees listed below, all of them checked out on the branch `{branch}`. Each subdirectory is a separate repo's worktree:

{repo_list}

## Ground rules

- **This workspace is the whole world.** Everything you may read or change lives under `{workspace_root}`. Other copies of these repos exist on this machine — Ryan's own checkouts, and Tethys's internal base clones under `{clone_dir}` — and they are *not* part of this task: they sit on different branches with different content. Don't read, grep, `cd` into, or reason from them.
- **If the task needs a repo that isn't listed above, stop and ask Ryan to add it.** He adds it with Tethys's "Add repo" action, which cuts that repo a worktree here on `{branch}`. Don't substitute another checkout, clone the repo, or guess at its contents — name the repo you need, say why, and wait for it to appear. In the registry but not in this workspace: {available_repos}.
- **The branch is shared, the repos are not.** A change spanning repos means a separate commit in each repo, each on `{branch}`. Nothing here is a monorepo; there is no root package manager, test runner, or git repo at this level.
- Each worktree keeps its git metadata in Tethys's base clone rather than beside the checkout, so `git` commands work normally from inside a worktree but the `.git` entry there is a file, not a directory.
"#;

/// Every token substituted in a workspace-doc body, for the `repos.toml` doc
/// comment and for warning about typo'd ones.
pub const PLACEHOLDERS: [&str; 5] = [
    "{branch}",
    "{repo_list}",
    "{available_repos}",
    "{workspace_root}",
    "{clone_dir}",
];

/// One repo present in the workspace, with its registry notes (if any).
struct RepoEntry<'a> {
    key: &'a str,
    claude_notes: Option<&'a str>,
}

/// Everything the template needs. Borrowed from the `Workspace` + registry.
struct WorkspaceDoc<'a> {
    /// Body template — the user's `[workspace_doc].body`, or [`DEFAULT_BODY`].
    body: &'a str,
    branch: &'a str,
    workspace_root: &'a Path,
    /// Repos checked out here, in the order they were added.
    repos: Vec<RepoEntry<'a>>,
    /// Registry repos *not* in this workspace — the set Claude may ask for.
    available_to_add: Vec<&'a str>,
    /// `<data_dir>/repos`, where Tethys keeps the base clones. Named in the
    /// ground rules because it's the other tempting place to go snooping.
    clone_dir: PathBuf,
}

/// Regenerate the workspace's `CLAUDE.md` from its repo links plus the
/// registry. Returns the path written, or `None` when there was nothing to do
/// (workspace has no repo links yet, its root is gone, or the file at that path
/// isn't ours to overwrite).
pub async fn regenerate(
    workspace: &Workspace,
    registry: &RepoRegistry,
    paths: &Paths,
) -> AppResult<Option<PathBuf>> {
    let Some(workspace_root) = workspace.root_buf() else {
        return Ok(None);
    };
    if !fs::try_exists(&workspace_root).await? {
        return Ok(None);
    }

    let repos: Vec<RepoEntry<'_>> = workspace
        .repo_links
        .iter()
        .map(|link| RepoEntry {
            key: &link.repo_key,
            claude_notes: registry
                .find_repo(&link.repo_key)
                .and_then(|r| r.claude_notes.as_deref())
                .map(str::trim)
                .filter(|s| !s.is_empty()),
        })
        .collect();
    let available_to_add: Vec<&str> = registry
        .repos
        .iter()
        .filter(|r| !workspace.repo_links.iter().any(|l| l.repo_key == r.key))
        .map(|r| r.key.as_str())
        .collect();

    let doc = WorkspaceDoc {
        body: registry.workspace_doc_body(),
        branch: &workspace.branch,
        workspace_root: &workspace_root,
        repos,
        available_to_add,
        clone_dir: paths.repos_clone_dir(),
    };

    let file_path = workspace_root.join(FILE_NAME);
    if !is_ours(&file_path).await? {
        warn!(
            path = %file_path.display(),
            "workspace root has a CLAUDE.md tethys didn't write; leaving it alone"
        );
        return Ok(None);
    }
    fs::write(&file_path, render(&doc)).await?;
    Ok(Some(file_path))
}

/// Whether we may write `path`: either it doesn't exist, or it exists and
/// carries our marker.
async fn is_ours(path: &Path) -> AppResult<bool> {
    match fs::read_to_string(path).await {
        Ok(s) => Ok(s.contains(MARKER)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(true),
        Err(e) => Err(AppError::Io(e)),
    }
}

/// Substitute [`PLACEHOLDERS`] into a body template. Anything else that looks
/// like a placeholder (`{some_word}`) is a typo or an unsupported token — it's
/// passed through untouched and logged, rather than swallowed, so the mistake is
/// visible in the generated file *and* the log. Braces in prose or code fences
/// are therefore always safe: no escaping to learn.
fn expand(body: &str, doc: &WorkspaceDoc<'_>) -> String {
    let repo_list = doc
        .repos
        .iter()
        .map(|r| format!("- `{}/` — the `{}` repo", r.key, r.key))
        .collect::<Vec<_>>()
        .join("\n");
    let available_repos = if doc.available_to_add.is_empty() {
        // Phrased to read correctly in a sentence like "…not in this
        // workspace: none.", so a body needs no conditional.
        "none — this workspace already spans every repo in the registry".to_string()
    } else {
        doc.available_to_add
            .iter()
            .map(|k| format!("`{k}`"))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let values = [
        ("{branch}", doc.branch.to_string()),
        ("{repo_list}", repo_list),
        ("{available_repos}", available_repos),
        ("{workspace_root}", doc.workspace_root.display().to_string()),
        ("{clone_dir}", doc.clone_dir.display().to_string()),
    ];
    debug_assert_eq!(values.len(), PLACEHOLDERS.len());

    let mut out = body.to_string();
    for (token, value) in values {
        out = out.replace(token, &value);
    }
    for unknown in unknown_placeholders(&out) {
        warn!(
            placeholder = %unknown,
            supported = ?PLACEHOLDERS,
            "unrecognized placeholder in [workspace_doc].body; left as-is"
        );
    }
    out
}

/// Find `{lower_snake_case}` tokens left over after substitution. Deliberately
/// narrow: it won't flag `{"json": true}`, `{}`, or `{Foo}`, only things shaped
/// like a placeholder we might have been expected to fill.
fn unknown_placeholders(rendered: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut rest = rendered;
    while let Some(open) = rest.find('{') {
        rest = &rest[open + 1..];
        let Some(close) = rest.find('}') else { break };
        let inner = &rest[..close];
        if !inner.is_empty()
            && inner
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        {
            let token = format!("{{{inner}}}");
            if !found.contains(&token) {
                found.push(token);
            }
        }
        rest = &rest[close + 1..];
    }
    found
}

fn render(doc: &WorkspaceDoc<'_>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{MARKER}");
    let _ = writeln!(
        out,
        "<!-- Tethys rewrites this file on workspace changes and at app start. \
         Edits here are lost. The body below comes from `[workspace_doc].body` in \
         repos.toml (or Tethys's built-in default when that's unset); per-repo \
         sections come from each repo's `claude_notes`. -->\n"
    );

    let _ = writeln!(out, "{}", expand(doc.body.trim_end(), doc));

    let notes: Vec<&RepoEntry<'_>> = doc
        .repos
        .iter()
        .filter(|r| r.claude_notes.is_some())
        .collect();
    if !notes.is_empty() {
        let _ = writeln!(out, "\n## Repo notes\n");
        let _ = writeln!(
            out,
            "From Ryan's repo registry. Notes for every repo in the workspace \
             are listed here, including repos other than the one you're \
             sitting in.\n"
        );
        for repo in notes {
            let _ = writeln!(out, "### `{}`\n", repo.key);
            // Notes are authored as prose/markdown in repos.toml; pass through
            // verbatim so lists and code fences survive.
            let _ = writeln!(out, "{}\n", repo.claude_notes.unwrap_or_default());
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::{Repo, WorkspaceDocConfig};
    use crate::state::{Origin, RepoLink, WorkspaceStatus};
    use chrono::Utc;

    fn repo(key: &str, notes: Option<&str>) -> Repo {
        Repo {
            key: key.into(),
            remote_url: format!("git@github.com:me/{key}.git"),
            default_branch: None,
            default_setup_script: None,
            setup_timeout_secs: None,
            copy_files: Vec::new(),
            claude_notes: notes.map(str::to_string),
            github_slug: None,
        }
    }

    fn workspace(root: &Path, keys: &[&str]) -> Workspace {
        Workspace {
            id: "ws-1".into(),
            branch: "feat/thing".into(),
            created_at: Utc::now(),
            repo_links: keys
                .iter()
                .map(|k| RepoLink {
                    repo_key: (*k).into(),
                    worktree_path: root.join(k),
                    setup_script_ran_at: None,
                    prs: Vec::new(),
                    dismissed: Vec::new(),
                    created_branch: true,
                })
                .collect(),
            session: None,
            claude_binary: None,
            origin: Origin::Ui,
            deleted_at: None,
            folder: None,
            status: WorkspaceStatus::Ready,
            notes: "private scratchpad".into(),
            blocked_by: None,
            artifacts: Vec::new(),
        }
    }

    fn registry(root: &Path, repos: Vec<Repo>) -> RepoRegistry {
        RepoRegistry {
            worktree_root: root.to_path_buf(),
            repos,
            workspace_doc: None,
        }
    }

    #[tokio::test]
    async fn lists_present_repos_absent_repos_and_notes() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            data_dir: tmp.path().join("data"),
        };
        let root = tmp.path().join("feat-thing");
        fs::create_dir_all(&root).await.unwrap();

        let ws = workspace(&root, &["nl-ai", "nl-backend"]);
        let reg = registry(
            tmp.path(),
            vec![
                repo("nl-ai", None),
                repo("nl-backend", Some("A global django container is usually running.")),
                repo("nl-web", None),
            ],
        );

        let written = regenerate(&ws, &reg, &paths).await.unwrap().unwrap();
        assert_eq!(written, root.join("CLAUDE.md"));
        let body = fs::read_to_string(&written).await.unwrap();

        assert!(body.starts_with(MARKER));
        assert!(body.contains("`feat/thing`"));
        assert!(body.contains("- `nl-ai/` — the `nl-ai` repo"));
        assert!(body.contains("- `nl-backend/` — the `nl-backend` repo"));
        // The one registry repo that isn't checked out here is offered by name.
        assert!(body.contains("not in this workspace: `nl-web`."));
        // Repo notes pass through verbatim under a per-repo heading.
        assert!(body.contains("### `nl-backend`"));
        assert!(body.contains("A global django container is usually running."));
        // No notes for nl-ai means no empty section for it.
        assert!(!body.contains("### `nl-ai`"));
        // Workspace notes stay private to the UI.
        assert!(!body.contains("private scratchpad"));
        // The two dirs Claude shouldn't wander into are named explicitly.
        assert!(body.contains(&root.display().to_string()));
        assert!(body.contains(&paths.repos_clone_dir().display().to_string()));
    }

    #[tokio::test]
    async fn available_repos_reads_as_a_sentence_when_there_are_none() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            data_dir: tmp.path().join("data"),
        };
        let root = tmp.path().join("feat-thing");
        fs::create_dir_all(&root).await.unwrap();

        let ws = workspace(&root, &["only"]);
        let reg = registry(tmp.path(), vec![repo("only", None)]);
        regenerate(&ws, &reg, &paths).await.unwrap().unwrap();

        let body = fs::read_to_string(root.join("CLAUDE.md")).await.unwrap();
        assert!(body.contains("not in this workspace: none — this workspace already spans every repo in the registry."));
    }

    /// A user-supplied body replaces the built-in prose but keeps the parts
    /// Tethys owns: the marker (so the file stays managed) and the notes it
    /// derives from `claude_notes`.
    #[tokio::test]
    async fn custom_body_from_repos_toml_replaces_the_default() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            data_dir: tmp.path().join("data"),
        };
        let root = tmp.path().join("feat-thing");
        fs::create_dir_all(&root).await.unwrap();

        let ws = workspace(&root, &["nl-ai", "nl-backend"]);
        let mut reg = registry(
            tmp.path(),
            vec![
                repo("nl-ai", None),
                repo("nl-backend", Some("django container is up")),
                repo("nl-web", None),
            ],
        );
        reg.workspace_doc = Some(WorkspaceDocConfig {
            body: "# ws {branch}\n\n{repo_list}\n\nrooted at {workspace_root}, \
                   clones at {clone_dir}, could also add {available_repos}. \
                   Braces like {\"a\": 1} and {Foo} survive; {typo_here} does too.\n"
                .into(),
        });

        regenerate(&ws, &reg, &paths).await.unwrap().unwrap();
        let body = fs::read_to_string(root.join("CLAUDE.md")).await.unwrap();

        assert!(body.starts_with(MARKER), "still Tethys-managed");
        assert!(body.contains("# ws feat/thing"));
        assert!(body.contains("- `nl-ai/` — the `nl-ai` repo"));
        assert!(body.contains("could also add `nl-web`."));
        assert!(body.contains(&format!("rooted at {}", root.display())));
        // None of the built-in prose leaks through.
        assert!(!body.contains("Ground rules"));
        assert!(!body.contains("whole world"));
        // Unsubstituted braces pass through verbatim — nothing to escape.
        assert!(body.contains("{\"a\": 1}"));
        assert!(body.contains("{Foo}"));
        assert!(body.contains("{typo_here}"));
        // Repo notes are still appended after the custom body.
        assert!(body.contains("### `nl-backend`"));
        assert!(body.contains("django container is up"));
    }

    #[test]
    fn unknown_placeholders_only_flags_placeholder_shaped_tokens() {
        assert_eq!(
            unknown_placeholders("{typo} and {another_one} and {typo}"),
            vec!["{typo}", "{another_one}"],
            "deduped, in order of appearance"
        );
        assert!(unknown_placeholders("{} {Foo} {a b} {\"json\": 1} { }").is_empty());
        assert!(unknown_placeholders("unterminated {oops").is_empty());
    }

    #[test]
    fn blank_custom_body_falls_back_to_the_default() {
        let mut reg = registry(Path::new("/tmp"), vec![]);
        assert_eq!(reg.workspace_doc_body(), DEFAULT_BODY);
        reg.workspace_doc = Some(WorkspaceDocConfig {
            body: "   \n\n".into(),
        });
        assert_eq!(reg.workspace_doc_body(), DEFAULT_BODY);
        reg.workspace_doc = Some(WorkspaceDocConfig {
            body: "  # mine\n".into(),
        });
        assert_eq!(reg.workspace_doc_body(), "# mine");
    }

    #[tokio::test]
    async fn rewrites_our_own_file_but_never_a_hand_written_one() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            data_dir: tmp.path().join("data"),
        };
        let root = tmp.path().join("feat-thing");
        fs::create_dir_all(&root).await.unwrap();
        let ws = workspace(&root, &["nl-ai"]);
        let reg = registry(tmp.path(), vec![repo("nl-ai", None)]);

        // Regenerating over our own output is fine and idempotent.
        regenerate(&ws, &reg, &paths).await.unwrap().unwrap();
        let first = fs::read_to_string(root.join("CLAUDE.md")).await.unwrap();
        regenerate(&ws, &reg, &paths).await.unwrap().unwrap();
        let second = fs::read_to_string(root.join("CLAUDE.md")).await.unwrap();
        assert_eq!(first, second);

        // A file we didn't write is left byte-for-byte intact.
        fs::write(root.join("CLAUDE.md"), "hand written\n")
            .await
            .unwrap();
        assert!(regenerate(&ws, &reg, &paths).await.unwrap().is_none());
        assert_eq!(
            fs::read_to_string(root.join("CLAUDE.md")).await.unwrap(),
            "hand written\n"
        );
    }

    #[tokio::test]
    async fn skips_workspace_without_links_or_root() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            data_dir: tmp.path().join("data"),
        };
        let reg = registry(tmp.path(), vec![repo("nl-ai", None)]);

        let mut ws = workspace(&tmp.path().join("gone"), &["nl-ai"]);
        // Root directory doesn't exist (purged worktrees, stale state).
        assert!(regenerate(&ws, &reg, &paths).await.unwrap().is_none());

        ws.repo_links.clear();
        assert!(regenerate(&ws, &reg, &paths).await.unwrap().is_none());
    }
}



